### ISSUE TITLE
Manually tracked goals not working with extension

### ISSUE THREAD

**Issue by j0hj0h** [adrianspeyer/Piwik-for-Magento#11]
I've some manual tracked goals on my shop, called via

```
_paq.push(['trackGoal', 1]);
```

... this works fine, as long as I integrate PIWIK with the standart code in the footer, but not, when it's done via the extension. I tried to track it down, but with the extension activated the PIWIK ajax callback doesn't go to piwik.php, but to the current shop-url with a bunch of GET-parameters. That's where I gave up and hope someone more into the architecture of this extension can give me a hint.

**Comment by meghashriKirani** [comment]
is this issue solved. As I am facing the same problem but not able find the solution. Can sombody give an example.

**Comment by adrianspeyer** [comment]
Yes code was updated
