### ISSUE TITLE
Missing orders from analytics

### ISSUE THREAD

**Issue by pierre-pizzetta** [adrianspeyer/Piwik-for-Magento#23]
I have around 300 orders per day on my store, but piwik-commerce barely register half of them.
We've even tried disabling the do-not-track-me feature. Anything to do to increase the tracking rate of orders?

**Comment by sprankhub** [comment]
And these orders definitely come directly from your store, so that the customers see the checkout success page? The only idea I have is that approx. half of them come from external marketplaces like eBay or Amazaon and are imported via a tool like M2ePro. Piwik will only track those orders, which are placed in the frontend of the store (so that the user sees the checkout success page).

**Comment by pierre-pizzetta** [comment]
They all come from the frontend store (>90% and the rest are order edits from admin), and most of them are Cash on Delivery so don't even go through a payment processing platform like Paypal and end up on success.
I guess there isn't a way to make the module call piwik tracking on event like "sales_order_save_after" would track the server and not customer, unless we can pass some extra params?
I'd love to have all of my sales in there.

**Comment by sprankhub** [comment]
Sounds weird. I do not have an idea at the moment why this happens. You may want to try [this alternative Piwik extension](https://github.com/integer-net/Piwik) and see if it works with it.

**Comment by adrianspeyer** [comment]
This plugin works the same way that GA works, so I don't believe if it does not go through a payment, there is an easy way to fix this.

**Comment by pierre-pizzetta** [comment]
I'll try to replicate orders no being registered on our testing platform and then give more details. I know you don't have a lot to go with right now, the ticket was initially to see if we were the only one to have the issue or if other people would share similar experiences. Thanks for taking a look into it though.
