### ISSUE TITLE
Revenue is not tracking for new piwik version

### ISSUE THREAD

**Issue by shogunjames** [adrianspeyer/Piwik-for-Magento#26]
Hi Sir,

I have installed the extension in magento and it was working perfectly for piwik version 1.10.1.

But when I upgraded piwik it stopped working.

Do you have any idea why this happened. What should I need to do to make it working in newer version of piwik.

**Comment by adrianspeyer** [comment]
please try solution suggested by Piwik, whihc to update protoype.js

https://github.com/piwik/piwik/issues/7945#issuecomment-114312376

**Comment by adrianspeyer** [comment]
I see you already got it working: https://github.com/piwik/piwik/issues/8113
