### ISSUE TITLE
Piwik subtotal with getGrandTotal or getBaseGrandTotal ?

### ISSUE THREAD

**Issue by bjoern-flagbit** [adrianspeyer/Piwik-for-Magento#28]
Here: src/app/code/community/PiwikMage/PiwikAnalytics/Block/Piwik.php on line 75 we have $order->getGrandTotal() but i think we need $order->getBaseGrandTotal() or?

You do that for "$result" some lines below. Also think about getBaseShippingAmount & getBaseShippingTaxAmount in line 75.

One of our customers have large subtotals because he has a lot of different currencies.

**Comment by adrianspeyer** [comment]
It does put out $order->getBaseGrandTotal(), so I am not sure the question. It will be clearer in the next version. You are free to modify for your needs :+1:
