### ISSUE TITLE
Search results page layout changed upon refresh

### ISSUE THREAD

**Issue by code-po8** [adrianspeyer/Piwik-for-Magento#29]
I submitted a case to Magento Enterprise support about an issue we're experiencing with the layout of the search results page breaking across the site.  Their engineer narrowed it down to the "PiwikMage_PiwikAnalytics extension" and told me to reach out to you.

The crux of the issue is that portions of the header are moved to the main content section of the page whenever any site visitor refreshes the search results page or copies and pastes the search result page's URL.  This appears to somehow corrupt the "Blocks HTML output" Magento cache, based on the fact that the only way to restore the proper page layout is to refresh this cache.

**Update:**
Magento Enterprise support deduced that this plugin caused the issue by process of elimination by disabling all plugins and re-enabling them one at a time.

**Page layout before a refresh:**
![screenshot1](https://cloud.githubusercontent.com/assets/11076259/10589857/3d018f0c-7673-11e5-8708-213e46e2e7d2.png)

**Page layout after a refresh:**
![screenshot2](https://cloud.githubusercontent.com/assets/11076259/10589851/3824407e-7673-11e5-82fd-0a5098fff7a8.png)

**Comment by sprankhub** [comment]
I do not think that this has anything to do with this extension. This seems totally unrelated.

**Comment by code-po8** [comment]
I also thought/think it's a bit of a stretch.  I'm trying to confirm with Magento support.  They are now less convinced.  I'll update this issue as I know more.

**Comment by code-po8** [comment]
Magento confirmed that it is a core issue, unrelated to this extension.  I apologize for the wild goose chase.
