### ISSUE TITLE
Product page: Only parent category is passed, not special category

### ISSUE THREAD

**Issue by hpvd** [adrianspeyer/Piwik-for-Magento#33]
In Magento a product can be within several categories.

e.g. very often a product belongs to special category but also to the parents category.
e.g. the "blue shirt with funny print" belongs to "blue t-shirts" and to "all t-shirts"

would be good to pass both categories to piwik.

Piwik supports up to 5 categories:

```
// all parameters are optional, but we recommend to set at minimum productSKU and productName
_paq.push(['setEcommerceView',
"9780786706211", // (required) SKU: Product unique identifier
"Endurance: Shackleton's Incredible Voyage", // (optional) Product name
"Adventure Books", // (optional) Product category, or array of up to 5 categories
20.11 // (optional) Product Price as displayed on the page
]);
_paq.push(['trackPageView']);
[...]
```
source:
https://piwik.org/docs/ecommerce-analytics/

**Comment by adrianspeyer** [comment]
Test this change: 

https://github.com/adrianspeyer/Piwik-for-Magento/issues/36
