### ISSUE TITLE
Magento 2.x Roadmap

### ISSUE THREAD

**Issue by devdesco-ceo** [adrianspeyer/Piwik-for-Magento#35]
Are you planning to port the extension to Magento 2.x version?

**Comment by adrianspeyer** [comment]
Not sure. I personally have no need for it.

**Comment by adrianspeyer** [comment]
I should add the original was built for a shop I was working on. I have moved on from that job, so I have no pressing need to create it. I am sure I will get to it, but I have no timeline (or time) to work on it at this point.

**Comment by devdesco-ceo** [comment]
Thank you for your straight answer!

**Comment by sprankhub** [comment]
You may want to ask the same question to the guys from IntegerNet. They also have a [Piwik extension](https://github.com/integer-net/Piwik).

**Comment by WebCenterShop-com** [comment]
Sin is really really very useful.

**Comment by adrianspeyer** [comment]
I have spoken to the team at Piwik and they will release an official Magento
Plugin as I no longer will be adding to this plugin. Please contact them at Piwik.pro to ask progress.
