### ISSUE TITLE
Only white site

### ISSUE THREAD

**Issue by heikostueber** [adrianspeyer/Piwik-for-Magento#38]
I get only a white site in magento admin, instead of the iframe (magento 1.9.1 , iframe is active). I use the latest Piwik version.

THX for help

**Comment by adrianspeyer** [comment]
Sorry can't replicate your issue.

**Comment by heikostueber** [comment]
Mmh, iframes are active for frontend and backend. The token ist correct. I Have no idea.

**Comment by adrianspeyer** [comment]
Maybe adblock?

**Comment by heikostueber** [comment]
Hi, I installed Opera and there it's working, if I want to see the blocked content.
In Safari I can't see any blocked content. I have to try it by configure Safari.

THX
